services:
  postgres:
      image: postgres
      # container_name: postgres
    
      ports:
        - 5432:5432

      env_file:
        - .env

      volumes:
        - postgres_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      # container_name: pgadmin

      ports:
        - 8080:80

      env_file:
        - .env

      volumes:
        - pgadmin-data:/var/lib/pgadmin

      depends_on:
        - postgres
volumes:
  postgres_data:
  pgadmin-data:

  