services:

  app:
    build: 
      context: ./server
      dockerfile: dockerfile
    
    env_file:
      - ./server/.env

    ports:
      - "3000:3000"

    volumes:
      - ./server:/app
      - /app/node_modules

    depends_on:
      - postgres


    command: yarn dev


  postgres:
      image: postgres
      # container_name: postgres
    
      ports:
        - 5432:5432

      env_file:
        - .env

      volumes:
        - postgres_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      # container_name: pgadmin

      ports:
        - 8080:80

      env_file:
        - .env

      volumes:
        - pgadmin-data:/var/lib/pgadmin

      depends_on:
        - postgres
volumes:
  postgres_data:
  pgadmin-data:

  